on:
  workflow_dispatch:
    inputs:
      revision:
        required: true
        default: main
jobs:
  build:
    runs-on: ubuntu-latest
    env:
      IMAGE_NAME: takutakahashi/build-test
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ inputs.revision }}
      - name: Branch name
        id: branch_name
        run: |
          echo ::set-output name=SOURCE_NAME::${GITHUB_REF#refs/*/}
          echo ::set-output name=SOURCE_BRANCH::${GITHUB_REF#refs/heads/}
          echo ::set-output name=SOURCE_TAG::${GITHUB_REF#refs/tags/}
          echo ::set-output name=IMAGE_NAME::${IMAGE_NAME}
          echo ::set-output name=SHA::${GITHUB_SHA}
      - name: Login to ghcr.io
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: takutakahashi
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: 'Build:image'
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: ghcr.io/${{ steps.branch_name.outputs.IMAGE_NAME }}:${{ steps.branch_name.outputs.SHA }}
      - run: sleep 600
